setwd("~/GitHub/Social_norm_meta_analysis/Analysis/")

df_main <- read.csv("Utility estimation/Output/Data/model_DG.csv")
df_nu   <- read.csv("Utility estimation/Output/Data/model_NU_DG.csv")

avg    <- as.list(df_main[df_main$treatment_id == "Average", ])
avg_nu <- as.list(df_nu[df_nu$treatment_id   == "Average", ])

fmt <- function(x, d = 2) formatC(round(x, d), format = "f", digits = d)

# Point estimate + 95% CI bounds, as three \newcommand macros: name, nameLo, nameHi
mac <- function(name, coeff, se, d = 2) {
  if (is.na(coeff) || is.na(se)) return(character(0))
  c(
    paste0("\\newcommand{\\", name,    "}{", fmt(coeff, d),               "}"),
    paste0("\\newcommand{\\", name, "Lo}{", fmt(coeff - 1.96 * se, d), "}"),
    paste0("\\newcommand{\\", name, "Hi}{", fmt(coeff + 1.96 * se, d), "}")
  )
}

# Single scalar (AIC, derived ratio), as one \newcommand macro
mac1 <- function(name, x, d = 2) {
  paste0("\\newcommand{\\", name, "}{", fmt(x, d), "}")
}

# Robustness check: re-pool sigma (Eq. 2) excluding kimbrough2016 and erkut2022,
# the two treatments where no dictator gave more than half their endowment.
# Re-aggregates the per-treatment estimates already in model_DG.csv (each
# treatment's clogit fit is independent, so no Stata re-run is needed).
excl_treatments <- c("2016Kim003_7", "2018Her061_9")
sigma_sub <- df_main[!(df_main$treatment_id %in% c("Average", excl_treatments)), ]
sigma_sub <- sigma_sub[!is.na(sigma_sub$sigmaDA), ]
w_sigma_excl  <- 1 / sigma_sub$se_sigmaDA^2
sigma_excl    <- sum(sigma_sub$sigmaDA * w_sigma_excl) / sum(w_sigma_excl)
se_sigma_excl <- sqrt(1 / sum(w_sigma_excl))

lines <- c(
  "% Auto-generated by Ancillary/make_macros.R -- do not edit by hand.",
  "% Re-run Ancillary/_run_macros.R after the pipeline updates, then re-copy",
  "% this file into the paper repo (same workflow as table_estimates.tex).",
  "",
  mac("deltaEqOne", avg$deltaS, avg$se_deltaS),
  mac1("aicEqOne", avg$S_AIC),
  "",
  mac("rhoEqTwo",   avg$rhoDA,   avg$se_rhoDA),
  mac("sigmaEqTwo", avg$sigmaDA, avg$se_sigmaDA),
  mac1("aicEqTwo", avg$DA_AIC),
  mac1("mrsEqTwo", avg$rhoDA / (1 - avg$rhoDA)),
  mac("sigmaEqTwoExcl", sigma_excl, se_sigma_excl),
  "",
  mac("deltaEqThree", avg$deltaN, avg$se_deltaN),
  mac("gammaEqThree", avg$gammaN, avg$se_gammaN),
  mac1("aicEqThree", avg$N_AIC),
  mac1("mrsEqThree", avg$gammaN / avg$deltaN),
  "",
  mac("rhoEqFour",   avg$rhoFU,   avg$se_rhoFU),
  mac("sigmaEqFour", avg$sigmaFU, avg$se_sigmaFU),
  mac("gammaEqFour", avg$gammaFU, avg$se_gammaFU),
  mac1("aicEqFour", avg$FU_AIC),
  mac1("mrsEqFour", avg$rhoFU / (1 - avg$rhoFU)),
  "",
  mac("rhoEqFive",   avg_nu$baserhoNU,   avg_nu$se_baserhoNU),
  mac("sigmaEqFive", avg_nu$basesigmaNU, avg_nu$se_basesigmaNU),
  mac("gammaEqFive", avg_nu$basegammaNU, avg_nu$se_basegammaNU),
  mac("etaEqFive",   avg_nu$baseetaNU,   avg_nu$se_baseetaNU),
  mac1("aicEqFive", avg_nu$baseNU_AIC),
  "",
  mac("rhoEqSix",   avg_nu$rhoNU,   avg_nu$se_rhoNU),
  mac("sigmaEqSix", avg_nu$sigmaNU, avg_nu$se_sigmaNU),
  mac("gammaEqSix", avg_nu$gammaNU, avg_nu$se_gammaNU),
  mac("etaEqSix",   avg_nu$etaNU,   avg_nu$se_etaNU),
  mac("nuEqSix",    avg_nu$nuNU,    avg_nu$se_nuNU),
  mac1("aicEqSix", avg_nu$NU_AIC)
)

writeLines(lines, "Utility estimation/Output/Tables/estimates_macros.tex")
cat("Written to Output/Tables/estimates_macros.tex\n")
