---
title: "dg_analysis"
author: "Sp & AG"
date: "19/1/2022"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, comment="", include=FALSE}
rm(list=ls())
library(ggplot2)
library(tidyverse)
library(mlogit)
library(sjmisc)
library(ggrepel)
library(readxl)
library(ggpubr)
library(survival)
library(sjPlot)
library(kableExtra)
library(car)
library(DT)
library(zoo)

setwd("../")
# read data 
getwd()
master <- read.csv("File_DB/Output/Treatment.csv") %>% 
  filter(Game_type == "DG") %>%
  subset.data.frame(subset = !(Standard_game %in% c("N")) & Choice_Method != "OnlyNorms" & StatusTreatment_Roma == "6-Complete" & Baseline %in% c(NA, 1))

beliefs <- read.csv("File_DB/Output/Subjects_beliefs.csv", sep = ",") %>%
  filter(treatment_id %in% levels(as.factor(paste(master$PaperID,"_",master$TreatmentCode, sep=""))))
choices <- read.csv("File_DB/Output/Subjects_choices.csv", sep = ",") %>%
  filter(treatment_id %in% levels(as.factor(paste(master$PaperID,"_",master$TreatmentCode, sep=""))))

```

# Individual-level analyses

```{r}
# belief dataset aggregated to get appropriateness for each action
beliefs_temp <- beliefs %>% subset.data.frame(subset = Design=="Between"&Game_type=="DG") %>% group_by(paper_id, treatment_id,scenarios) %>% summarise(avg_kw = mean(KW_Normative, rm.na=T),
                                                                                                                                                       sd_kw = sd(KW_Normative, na.rm = T))
Kim003_interpolation <- beliefs_temp %>% subset.data.frame(paper_id == "2016Kim003" & treatment_id == "2016Kim003_7") %>% 
  rbind.data.frame(data.frame(paper_id="2016Kim003", treatment_id="2016Kim003_7", scenarios=seq(1,15,2), avg_kw=NA, sd_kw=NA)) %>% 
  ungroup() %>% arrange(scenarios) %>%
  mutate(KW_Normative = na.approx(avg_kw, maxgap = 1, rule = 1),
         sd_KW = na.approx(sd_kw, maxgap = 1, rule = 1))
mean_beliefs <- beliefs %>% merge.data.frame(Kim003_interpolation, all = T) %>% group_by(paper_id, treatment_id, scenarios) %>% summarise(mean_app=mean(KW_Normative), sd_app=mean(sd_KW))
individual_db <- choices %>% merge.data.frame(mean_beliefs)%>% mutate(payoff=endowment-scenarios)
master$treatment_id = paste(master$PaperID,"_",master$TreatmentCode, sep="")
# mlogit
for (i in levels(as.factor(individual_db$treatment_id))) {
  model=mclogit::mclogit(cbind(A,choice)~ payoff + mean_app + sd_app, data=individual_db%>% filter(treatment_id==i))
  print(i)
print(summary(model))
}
#mdata=mlogit.data(individual_db, chid.var = "scenarios")
#mlogit()
```

